// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEAokvA1m2HCy3zqgi4HlCFI19H9Qzv6U',
    appId: '1:558402562736:web:3396c18899ba42236ae975',
    messagingSenderId: '558402562736',
    projectId: 'expensifyai-7f03a',
    authDomain: 'expensifyai-7f03a.firebaseapp.com',
    storageBucket: 'expensifyai-7f03a.firebasestorage.app',
    measurementId: 'G-C3Z3NSELB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcjwfGQ1Su86N0nVaDEblH6Kz01mKKjs',
    appId: '1:558402562736:android:95c3bb92e33bfc316ae975',
    messagingSenderId: '558402562736',
    projectId: 'expensifyai-7f03a',
    storageBucket: 'expensifyai-7f03a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKaWBhNaXHTqLdO0ixxBGFNGOWz7abQc',
    appId: '1:558402562736:ios:10e5cffdc3aa75ab6ae975',
    messagingSenderId: '558402562736',
    projectId: 'expensifyai-7f03a',
    storageBucket: 'expensifyai-7f03a.firebasestorage.app',
    iosBundleId: 'com.example.expensifyAiClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWKaWBhNaXHTqLdO0ixxBGFNGOWz7abQc',
    appId: '1:558402562736:ios:10e5cffdc3aa75ab6ae975',
    messagingSenderId: '558402562736',
    projectId: 'expensifyai-7f03a',
    storageBucket: 'expensifyai-7f03a.firebasestorage.app',
    iosBundleId: 'com.example.expensifyAiClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEAokvA1m2HCy3zqgi4HlCFI19H9Qzv6U',
    appId: '1:558402562736:web:615bc819c3faf79a6ae975',
    messagingSenderId: '558402562736',
    projectId: 'expensifyai-7f03a',
    authDomain: 'expensifyai-7f03a.firebaseapp.com',
    storageBucket: 'expensifyai-7f03a.firebasestorage.app',
    measurementId: 'G-KM6DN532NR',
  );
}
